# Use postgres/example user/password credentials
services:

  db:
    image: rafaelleal18/web2:atividade6-v1
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: "ponto123"
      POSTGRES_USER: sistemaDePonto
      POSTGRES_DB: sistemaDePonto
    ports:
      - 5432:5432
